title: Caio Martins # your name here
logo: "/Foto_perfil/foto_perfil.jpg" # your photo here

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/caiosm01/">LinkedIn</a> |
  <a href="https://caiosm01.github.io/caiosm1.github.io/">Portfólio</a> |
  <a href="https://github.com/caiosm01">GitHub</a> |
  <a href="mailto:caiosm180@gmail.com">E-mail</a>
  </p>
  
  <p align="center">
   Olá, tudo bem? Navegue pelo meu portfólio de projetos e conheça um pouco mais sobre minhas habilidades!
   
   </p>
   <p align="center">
   <a href="#projetos-analise">؜؜Projetos de Análise de Dados</a> <br>
   <a href="#projetos-engenharia">Projetos de Engenharia de Dados</a> <br>
   <a href="#projetos-automacao">Automação de tarefas</a> <br>
   </p> 
   </p>
   <p align="center">
   <br><br>
   </p>
theme: jekyll-theme-minimal
